# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ddApiKey: $(DD_API_KEY)
  DD_ENV: CI

# Declare the datadog agent as a resource to be used as a pipeline service
resources:
  containers:
  - container: dd_agent
    image: datadog/agent
    ports:
    - 8126:8126
    env:
      DD_API_KEY: $(ddApiKey)
      #DD_INSIDE_CI: true

services:
  dd_agent: dd_agent

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# **********************************************************

# Ensure dotnet 5.0 SDK (required to install dd-trace CLI)
- task: UseDotNet@2
  displayName: (CI-VISIBILITY) Install dotnet core SDK 5
  inputs:
    packageType: sdk
    version: 5.x

# Install dotnet dd-trace tool
- script: dotnet tool update -g dd-trace
  displayName: (CI-VISIBILITY) Install dd-trace dotnet tool

# Configure pipeline to use CI Visibility
- script: dd-trace --set-ci
  displayName: (CI-VISIBILITY) Configure pipeline to use CI Visibility

- script: "dir env:"
  displayName: List Environment Variables

# **********************************************************

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
