# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ddApiKey: $(DD_API_KEY)

  # Environment CI.
  DD_ENV: CI

  # Use CI Visibility Agentless mode.
  DD_CIVISIBILITY_AGENTLESS_ENABLED: 1

  #Enable debug logs
  DD_TRACE_DEBUG: 1

  #Exclude Process
  DD_PROFILER_EXCLUDE_PROCESSES: DTAExecutionHost.exe;powershell.exe

  #Stop Git upload (is returning exit code 128)
  DD_CIVISIBILITY_GIT_UPLOAD_ENABLED: 0

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


# **********************************************************

# Ensure dotnet 6.0 SDK (required to install dd-trace CLI)
- task: UseDotNet@2
  displayName: (CI-VISIBILITY) Install dotnet core SDK 6
  inputs:
    packageType: sdk
    version: 6.x

# Install dotnet dd-trace tool
- script: dotnet tool update -g dd-trace
  displayName: (CI-VISIBILITY) Install dd-trace dotnet tool

# Ensure logs folder exists
- script: mkdir "%PROGRAMDATA%\Datadog .NET Tracer\logs"
  displayName: (CI-VISIBILITY) Create Logs folder
  condition: always()

# Configure pipeline to use CI Visibility
- script: dd-trace ci configure
  displayName: (CI-VISIBILITY) Configure pipeline to use CI Visibility

# **********************************************************
- task: VSTest@2
  env:
    DD_API_KEY: $(ddApiKey)
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
# **********************************************************

# Ensure logs folder exists
- script: dir "%PROGRAMDATA%\Datadog .NET Tracer\logs"
  displayName: (CI-VISIBILITY) Create Logs folder
  condition: always()

- task: PublishBuildArtifacts@1
  condition: always()
  inputs:
    pathToPublish: '$(PROGRAMDATA)\\Datadog .NET Tracer\\logs'
    artifactName: logs


# **********************************************************

