name: Test

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      datadog-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
        - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Install dd-trace
      run: |
           dotnet tool install -g dd-trace
           echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH           
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
